<?php

declare(strict_types=1);

/*
 * This file is part of Biurad opensource projects.
 *
 * PHP version 7.2 and above required
 *
 * @author    Divine Niiquaye Ibok <divineibok@gmail.com>
 * @copyright 2019 Biurad Group (https://biurad.com/)
 * @license   https://opensource.org/licenses/BSD-3-Clause License
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Biurad\Framework\Debug\Event;

?>

<h1>Events Listeners (<?php echo $this->data['listeners_count']; ?>)</h1>
<div class="tracy-inner">
    <div class="tracy-inner-container">
        <h2><strong>Called Listeners</strong></h2>
        <?php if (empty($this->data['called_listeners'])): ?>
            <div class="empty">
                <p>No events have been recorded. Check that debugging is enabled in the kernel.</p>
            </div>
        <?php else: ?>
            <table>
                <thead>
                    <tr>
                        <th scope="col">Event name</th>
                        <th scope="col">Priority</th>
                        <th scope="col">Duration</th>
                        <th scope="col">Listener</th>
                    </tr>
                </thead>

                <tbody>
                    <?php foreach ($this->data['called_listeners'] as $listener) : ?>
                        <tr>
                            <td><?= $listener['event'] ?></td>
                            <td><?= $listener['priority'] ?></td>
                            <td><?= $listener['duration'] ?></td>
                            <td><?= $listener['pretty'] ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php endif; ?>

        <h2><strong>Not Called Listeners</strong></h2>
        <div class="tracy-inner-container">
            <?php if (empty($this->data['not_called_listeners'])): ?>
                <p>
                    All listeners were called for this request or an error occurred
                    when trying to collect uncalled listeners (in which case check the
                    logs to get more information).
                </p>
            <?php else: ?>
                <table>
                    <thead>
                        <tr>
                            <th scope="col">Event name</th>
                            <th scope="col">Priority</th>
                            <th scope="col">Duration</th>
                            <th scope="col">Listener</th>
                        </tr>
                    </thead>

                    <tbody>
                        <?php foreach ($this->data['not_called_listeners'] as $listener) : ?>
                            <tr>
                                <td><?= $listener['event'] ?></td>
                                <td><?= $listener['priority'] ?></td>
                                <td><?= $listener['duration'] ?></td>
                                <td><?= $listener['pretty'] ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            <?php endif; ?>
        </div>

        <h2><strong>Orphaned Events</strong></h2>
        <div class="tracy-inner-container">
            <?php if (empty($this->data['orphaned_events'])): ?>
                <p>
                    All dispatched events were handled or an error occurred
                    when trying to collect orphaned events (in which case check the
                    logs to get more information).
                </p>
            <?php else: ?>
                <table>
                    <thead>
                        <tr>
                            <th scope="col">Event name</th>
                            <th scope="col">Priority</th>
                            <th scope="col">Duration</th>
                            <th scope="col">Listener</th>
                        </tr>
                    </thead>

                    <tbody>
                        <?php foreach ($this->data['orphaned_events'] as $listener) : ?>
                            <tr>
                                <td><?= $listener['event'] ?></td>
                                <td><?= $listener['priority'] ?></td>
                                <td><?= $listener['duration'] ?></td>
                                <td><?= $listener['pretty'] ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            <?php endif; ?>
        </div>
    </div>
</div>
