<?php

declare(strict_types=1);

/*
 * This file is part of Biurad opensource projects.
 *
 * PHP version 7.2 and above required
 *
 * @author    Divine Niiquaye Ibok <divineibok@gmail.com>
 * @copyright 2019 Biurad Group (https://biurad.com/)
 * @license   https://opensource.org/licenses/BSD-3-Clause License
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Biurad\Framework\Debug\Event;

use Tracy\Helpers;

?>

<h1>Events Listeners (<?php echo count($listeners); ?>)</h1>
<div class="tracy-inner">
    <div class="tracy-inner-container">
        <table>
            <thead>
                <tr>
                    <th>Events</th>
                    <th>Time Laps</th>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($events as $index => $event) : ?>
                    <tr>
                        <td><?php echo Helpers::escapeHtml($event['event']); ?></td>
                        <td><?php echo $event['duration']; ?></td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>
