<?php

declare(strict_types=1);

/*
 * This file is part of Biurad opensource projects.
 *
 * PHP version 7.2 and above required
 *
 * @author    Divine Niiquaye Ibok <divineibok@gmail.com>
 * @copyright 2019 Biurad Group (https://biurad.com/)
 * @license   https://opensource.org/licenses/BSD-3-Clause License
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Biurad\Framework\Debug\Route;

use Tracy;
use Tracy\Dumper;
use Tracy\Helpers;

?>
<style class="tracy-debug">
    #tracy-debug .nette-RoutingPanel table {
        font: 9pt/1.5 Consolas, monospace;
    }

    #tracy-debug .nette-RoutingPanel .yes td {
        background: #BDE678 !important;
    }

    #tracy-debug .nette-RoutingPanel .may td {
        background: #C1D3FF !important;
    }

    #tracy-debug .nette-RoutingPanel td:first-child {
        width: 20px;
    }

    #tracy-debug .nette-RoutingPanel td:nth-child(2) {
        white-space: nowrap;
    }

    #tracy-debug .nette-RoutingPanel pre,
    #tracy-debug .nette-RoutingPanel code {
        display: inline;
        background: transparent;
    }

    #tracy-debug .nette-RoutingPanel-rel {
        background: #eee;
        white-space: nowrap;
    }
</style>

<h1>
    <?php if ($matched === null) : ?>
        <?php echo is_string($routers) ? 'Method not found' : 'No route'; ?>
    <?php elseif (isset($matched['presenter'])) : ?>
        <?php echo ($matched['presenter'] instanceof \Closure) ? 'Closure:type' : $matched['presenter']; ?>
    <?php endif ?>
</h1>

<div class="tracy-inner nette-RoutingPanel">
    <div class="tracy-inner-container">
        <?php if (empty($routers)) : ?>
            <p>No routers defined for current uri: <?php echo $url; ?>.</p>
        <?php elseif (is_string($routers)) : ?>
            <p><?php echo $routers . ", not [$method]"; ?></p>
        <?php else : ?>
            <table>
                <thead>
                    <tr>
                        <th></th>
                        <th>Name</th>
                        <th>Matched as</th>
                        <th>Route</th>
                    </tr>
                </thead>

                <tbody>
                    <?php foreach ($routers as $router) : ?>
                        <tr class="<?php echo $router['matched'] ?>">
                            <td><?php echo $router['matched'] === 'yes' ? '✓' : ($router['matched'] === 'may' ? '≈' : ''); ?></td>

                            <td><code title="<?php echo Helpers::escapeHtml(get_class($router['route'])); ?>"> <?php echo Helpers::escapeHtml($router['name']); ?></code></td>

                            <td><?php if ($router['params']) : ?><code>
                                <?php $params = $router['params']; ?>
                                <?php if (isset($params['presenter'])) : ?>
                                    <strong><?php echo ($matched['presenter'] instanceof \Closure) ? 'Closure:type' : $matched['presenter']; ?></strong><br />
                                <?php endif ?>
                                <?php foreach ($router['params'] as $key => $value) : ?>
                                    <?php if ('presenter' === $key) : ?>
                                        <?php continue; ?>
                                    <?php endif ?>
                                    <?= Helpers::escapeHtml($key), '&nbsp;=&nbsp;', is_string($value) ? Helpers::escapeHtml($value) . '<br />' : Dumper::toHtml($value, [Dumper::COLLAPSE => true, Dumper::LIVE => true]); ?>
                                <?php endforeach ?>
                                </code><?php endif ?>
                            </td>

                            <td><code>
                                    <?php echo Dumper::toHtml($router['route'], [Dumper::COLLAPSE => true, Dumper::LIVE => true]); ?>
                                </code>
                            </td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        <?php endif ?>
    </div>

    <div class="tracy-inner-container">
        <p>
            <code><?= Helpers::escapeHtml($method) ?></code>
            <code><wbr><span class="nette-RoutingPanel-rel"><?= str_replace(['&amp;', '?'], ['<wbr>&amp;', '<wbr>?'], Helpers::escapeHtml($url)) ?></span></code>
        </p>

        <?php if ($source && is_string($source->getFileName())) : ?>
            <p><a href="<?php echo Helpers::escapeHtml(Tracy\Helpers::editorUri($source->getFileName(), $source->getStartLine())) ?>"><?php echo ($source instanceof \ReflectionClass || $source instanceof \ReflectionFunction) ? $source->getName() : $source->getDeclaringClass()->getName() . '::' . $source->getName() . '()' ?></a></p>
        <?php endif ?>
    </div>
</div>
