<?php

declare(strict_types=1);

/*
 * This file is part of Biurad opensource projects.
 *
 * PHP version 7.2 and above required
 *
 * @author    Divine Niiquaye Ibok <divineibok@gmail.com>
 * @copyright 2019 Biurad Group (https://biurad.com/)
 * @license   https://opensource.org/licenses/BSD-3-Clause License
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Biurad\Framework\Debug\Template;

?>

<style>
    #tracy-debug .debug-tracy-template-bar tr td,
    #tracy-debug .debug-tracy-template-bar tr th
    {
        text-align: center;
    }
</style>

<h1>UI Templates (<?php echo $duration ?>)</h1>
<div class="tracy-inner tracy-template-bar">
    <h2><strong>Templates Metrics</strong></h2>
    <table class="debug-tracy-template-bar">
        <tr>
            <td><?php echo $duration ?></td>
            <td><?php echo $memory ?></td>
            <td><?php echo $this->templateCount ?></td>
            <td><?php echo $this->renderCount ?></td>
        </tr>
        <tr>
            <th scope="col">Render time</th>
            <th scope="col">Memory usage</th>
            <th scope="col">Template calls</th>
            <th scope="col">Renders calls</th>
        </tr>
    </table>

    <h2><strong>Templates Rendered</strong></h2>
    <table>
        <tr>
            <th scope="col">Template name</th>
            <th scope="col">Render time</th>
            <th scope="col">Memory usage</th>
        </tr>
        <?php foreach ($this->templates as $tpl): ?>
            <tr>
                <td><?php echo $tpl['name'] ?></td>
                <td><?php echo $tpl['duration'] ?></td>
                <td><?php echo $tpl['memory'] ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
